# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Just another day
email: bonapetite.au@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4001/" # the base hostname & protocol for your site
port: 4001
about-me: I am a full-stack software developer working in Brisbane.  My passion is data analytics, cloud technologies.My favourite food is Sand Crab & Snapper Risotto and Singaporean Fish Head Noodle.
# Build settings
markdown: kramdown

